// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_cox_joint_lambda
double cpp_cox_joint_lambda(double t);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_lambda(SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_lambda(t));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_Lambda
double cpp_cox_joint_Lambda(double t);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_Lambda(SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_Lambda(t));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_log_normal_pdf
double cpp_cox_joint_log_normal_pdf(double t, double m, double s, double pi);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_log_normal_pdf(SEXP tSEXP, SEXP mSEXP, SEXP sSEXP, SEXP piSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type pi(piSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_log_normal_pdf(t, m, s, pi));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_d_log_normal_pdf
double cpp_cox_joint_d_log_normal_pdf(double t, double m, double s);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_d_log_normal_pdf(SEXP tSEXP, SEXP mSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_d_log_normal_pdf(t, m, s));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_dd_log_normal_pdf
double cpp_cox_joint_dd_log_normal_pdf(double s);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_dd_log_normal_pdf(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_dd_log_normal_pdf(s));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_ddm_log_normal_pdf
double cpp_cox_joint_ddm_log_normal_pdf(double s);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_ddm_log_normal_pdf(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_ddm_log_normal_pdf(s));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_est_Lambda
double cpp_cox_joint_est_Lambda(double t, arma::mat data_compl, arma::colvec est_compl, arma::colvec ipw_compl);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_est_Lambda(SEXP tSEXP, SEXP data_complSEXP, SEXP est_complSEXP, SEXP ipw_complSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type est_compl(est_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_est_Lambda(t, data_compl, est_compl, ipw_compl));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_est_lambda
arma::colvec cpp_cox_joint_est_lambda(arma::mat data_compl, arma::colvec est_compl, arma::colvec ipw_compl);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_est_lambda(SEXP data_complSEXP, SEXP est_complSEXP, SEXP ipw_complSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type est_compl(est_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_est_lambda(data_compl, est_compl, ipw_compl));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_s0_true
arma::colvec cpp_cox_joint_s0_true(arma::colvec beta, arma::colvec t, arma::mat data_compl, arma::colvec est_compl, arma::colvec ipw_compl);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_s0_true(SEXP betaSEXP, SEXP tSEXP, SEXP data_complSEXP, SEXP est_complSEXP, SEXP ipw_complSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type est_compl(est_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_s0_true(beta, t, data_compl, est_compl, ipw_compl));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_s1_true
arma::mat cpp_cox_joint_s1_true(arma::colvec beta, arma::colvec t, arma::mat data_compl, arma::colvec est_compl, arma::colvec ipw_compl);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_s1_true(SEXP betaSEXP, SEXP tSEXP, SEXP data_complSEXP, SEXP est_complSEXP, SEXP ipw_complSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type est_compl(est_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_s1_true(beta, t, data_compl, est_compl, ipw_compl));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_s0_org
arma::colvec cpp_cox_joint_s0_org(arma::colvec beta, arma::colvec t, arma::mat data_compl, arma::colvec ipw_compl);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_s0_org(SEXP betaSEXP, SEXP tSEXP, SEXP data_complSEXP, SEXP ipw_complSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_s0_org(beta, t, data_compl, ipw_compl));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_s1_org
arma::mat cpp_cox_joint_s1_org(arma::colvec beta, arma::colvec t, arma::mat data_compl, arma::colvec ipw_compl);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_s1_org(SEXP betaSEXP, SEXP tSEXP, SEXP data_complSEXP, SEXP ipw_complSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_s1_org(beta, t, data_compl, ipw_compl));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_s2_org
arma::cube cpp_cox_joint_s2_org(arma::colvec beta, arma::colvec t, arma::mat data_compl, arma::colvec ipw_compl);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_s2_org(SEXP betaSEXP, SEXP tSEXP, SEXP data_complSEXP, SEXP ipw_complSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_s2_org(beta, t, data_compl, ipw_compl));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_s0_work
arma::colvec cpp_cox_joint_s0_work(arma::colvec beta, arma::colvec t, arma::mat data_all);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_s0_work(SEXP betaSEXP, SEXP tSEXP, SEXP data_allSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_s0_work(beta, t, data_all));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_s1_work
arma::mat cpp_cox_joint_s1_work(arma::colvec beta, arma::colvec t, arma::mat data_all);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_s1_work(SEXP betaSEXP, SEXP tSEXP, SEXP data_allSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_s1_work(beta, t, data_all));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_s2_work
arma::cube cpp_cox_joint_s2_work(arma::colvec beta, arma::colvec t, arma::mat data_all);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_s2_work(SEXP betaSEXP, SEXP tSEXP, SEXP data_allSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_s2_work(beta, t, data_all));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_score_work_modelX
arma::colvec cpp_cox_joint_score_work_modelX(arma::colvec beta, arma::mat data, arma::mat data_all, arma::mat data_compl, arma::colvec predX, double seX, arma::colvec grid, arma::colvec weight, double pi, arma::colvec est_compl, arma::colvec ipw_compl, arma::colvec ipw);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_score_work_modelX(SEXP betaSEXP, SEXP dataSEXP, SEXP data_allSEXP, SEXP data_complSEXP, SEXP predXSEXP, SEXP seXSEXP, SEXP gridSEXP, SEXP weightSEXP, SEXP piSEXP, SEXP est_complSEXP, SEXP ipw_complSEXP, SEXP ipwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type predX(predXSEXP);
    Rcpp::traits::input_parameter< double >::type seX(seXSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< double >::type pi(piSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type est_compl(est_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw(ipwSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_score_work_modelX(beta, data, data_all, data_compl, predX, seX, grid, weight, pi, est_compl, ipw_compl, ipw));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_score_work_modelX_vec
arma::mat cpp_cox_joint_score_work_modelX_vec(arma::colvec beta, arma::mat data, arma::mat data_all, arma::mat data_compl, arma::colvec predX, double seX, arma::colvec grid, arma::colvec weight, double pi, arma::colvec est_compl, arma::colvec ipw_compl, arma::colvec ipw);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_score_work_modelX_vec(SEXP betaSEXP, SEXP dataSEXP, SEXP data_allSEXP, SEXP data_complSEXP, SEXP predXSEXP, SEXP seXSEXP, SEXP gridSEXP, SEXP weightSEXP, SEXP piSEXP, SEXP est_complSEXP, SEXP ipw_complSEXP, SEXP ipwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type predX(predXSEXP);
    Rcpp::traits::input_parameter< double >::type seX(seXSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< double >::type pi(piSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type est_compl(est_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw(ipwSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_score_work_modelX_vec(beta, data, data_all, data_compl, predX, seX, grid, weight, pi, est_compl, ipw_compl, ipw));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_score_work_trueX
arma::colvec cpp_cox_joint_score_work_trueX(arma::colvec beta, arma::mat data, arma::mat data_all, arma::mat data_compl, arma::colvec grid, arma::colvec weight, double sde, double theta, double sdxz, double pi, arma::colvec ipw_compl, arma::colvec ipw);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_score_work_trueX(SEXP betaSEXP, SEXP dataSEXP, SEXP data_allSEXP, SEXP data_complSEXP, SEXP gridSEXP, SEXP weightSEXP, SEXP sdeSEXP, SEXP thetaSEXP, SEXP sdxzSEXP, SEXP piSEXP, SEXP ipw_complSEXP, SEXP ipwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< double >::type sde(sdeSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sdxz(sdxzSEXP);
    Rcpp::traits::input_parameter< double >::type pi(piSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw(ipwSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_score_work_trueX(beta, data, data_all, data_compl, grid, weight, sde, theta, sdxz, pi, ipw_compl, ipw));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_score_work_trueX_vec
arma::mat cpp_cox_joint_score_work_trueX_vec(arma::colvec beta, arma::mat data, arma::mat data_all, arma::mat data_compl, arma::colvec grid, arma::colvec weight, double sde, double theta, double sdxz, double pi, arma::colvec ipw_compl, arma::colvec ipw);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_score_work_trueX_vec(SEXP betaSEXP, SEXP dataSEXP, SEXP data_allSEXP, SEXP data_complSEXP, SEXP gridSEXP, SEXP weightSEXP, SEXP sdeSEXP, SEXP thetaSEXP, SEXP sdxzSEXP, SEXP piSEXP, SEXP ipw_complSEXP, SEXP ipwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< double >::type sde(sdeSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sdxz(sdxzSEXP);
    Rcpp::traits::input_parameter< double >::type pi(piSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw(ipwSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_score_work_trueX_vec(beta, data, data_all, data_compl, grid, weight, sde, theta, sdxz, pi, ipw_compl, ipw));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_score_org
arma::colvec cpp_cox_joint_score_org(arma::colvec beta, arma::mat data, arma::mat data_all, arma::mat data_compl, arma::colvec ipw_compl, arma::colvec ipw);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_score_org(SEXP betaSEXP, SEXP dataSEXP, SEXP data_allSEXP, SEXP data_complSEXP, SEXP ipw_complSEXP, SEXP ipwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw(ipwSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_score_org(beta, data, data_all, data_compl, ipw_compl, ipw));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_score_org_vec
arma::mat cpp_cox_joint_score_org_vec(arma::colvec beta, arma::mat data, arma::mat data_all, arma::mat data_compl, arma::colvec ipw_compl, arma::colvec ipw);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_score_org_vec(SEXP betaSEXP, SEXP dataSEXP, SEXP data_allSEXP, SEXP data_complSEXP, SEXP ipw_complSEXP, SEXP ipwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw(ipwSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_score_org_vec(beta, data, data_all, data_compl, ipw_compl, ipw));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_info_org
arma::mat cpp_cox_joint_info_org(arma::colvec beta, arma::mat data_all, arma::mat data_compl, arma::colvec ipw_compl);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_info_org(SEXP betaSEXP, SEXP data_allSEXP, SEXP data_complSEXP, SEXP ipw_complSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_info_org(beta, data_all, data_compl, ipw_compl));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_score_work_coxph
arma::colvec cpp_cox_joint_score_work_coxph(arma::colvec beta, arma::mat data, arma::mat data_all, arma::colvec ipw);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_score_work_coxph(SEXP betaSEXP, SEXP dataSEXP, SEXP data_allSEXP, SEXP ipwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw(ipwSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_score_work_coxph(beta, data, data_all, ipw));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_score_work_coxph_vec
arma::mat cpp_cox_joint_score_work_coxph_vec(arma::colvec beta, arma::mat data, arma::mat data_all, arma::colvec ipw);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_score_work_coxph_vec(SEXP betaSEXP, SEXP dataSEXP, SEXP data_allSEXP, SEXP ipwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw(ipwSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_score_work_coxph_vec(beta, data, data_all, ipw));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_joint_info_work_coxph
arma::mat cpp_cox_joint_info_work_coxph(arma::colvec beta, arma::mat data_all);
RcppExport SEXP _twoStep2Phase_cpp_cox_joint_info_work_coxph(SEXP betaSEXP, SEXP data_allSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_joint_info_work_coxph(beta, data_all));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_opt_lambda
double cpp_cox_opt_lambda(double t);
RcppExport SEXP _twoStep2Phase_cpp_cox_opt_lambda(SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_opt_lambda(t));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_opt_Lambda
double cpp_cox_opt_Lambda(double t);
RcppExport SEXP _twoStep2Phase_cpp_cox_opt_Lambda(SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_opt_Lambda(t));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_opt_log_kernel_fn
double cpp_cox_opt_log_kernel_fn(double t, double h, double pi);
RcppExport SEXP _twoStep2Phase_cpp_cox_opt_log_kernel_fn(SEXP tSEXP, SEXP hSEXP, SEXP piSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type pi(piSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_opt_log_kernel_fn(t, h, pi));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_opt_log_normal_pdf
double cpp_cox_opt_log_normal_pdf(double t, double m, double s, double pi);
RcppExport SEXP _twoStep2Phase_cpp_cox_opt_log_normal_pdf(SEXP tSEXP, SEXP mSEXP, SEXP sSEXP, SEXP piSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type pi(piSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_opt_log_normal_pdf(t, m, s, pi));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_opt_est_Lambda
double cpp_cox_opt_est_Lambda(double t, arma::mat data_compl, double est_compl, arma::colvec ipw_compl);
RcppExport SEXP _twoStep2Phase_cpp_cox_opt_est_Lambda(SEXP tSEXP, SEXP data_complSEXP, SEXP est_complSEXP, SEXP ipw_complSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< double >::type est_compl(est_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_opt_est_Lambda(t, data_compl, est_compl, ipw_compl));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_opt_est_lambda
arma::colvec cpp_cox_opt_est_lambda(arma::mat data_compl, double est_compl, arma::colvec ipw_compl);
RcppExport SEXP _twoStep2Phase_cpp_cox_opt_est_lambda(SEXP data_complSEXP, SEXP est_complSEXP, SEXP ipw_complSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< double >::type est_compl(est_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_opt_est_lambda(data_compl, est_compl, ipw_compl));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_opt_s0_true
arma::colvec cpp_cox_opt_s0_true(double beta, arma::colvec t, arma::mat data_compl, double est_compl, arma::colvec ipw_compl);
RcppExport SEXP _twoStep2Phase_cpp_cox_opt_s0_true(SEXP betaSEXP, SEXP tSEXP, SEXP data_complSEXP, SEXP est_complSEXP, SEXP ipw_complSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< double >::type est_compl(est_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_opt_s0_true(beta, t, data_compl, est_compl, ipw_compl));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_opt_s1_true
arma::colvec cpp_cox_opt_s1_true(double beta, arma::colvec t, arma::mat data_compl, double est_compl, arma::colvec ipw_compl);
RcppExport SEXP _twoStep2Phase_cpp_cox_opt_s1_true(SEXP betaSEXP, SEXP tSEXP, SEXP data_complSEXP, SEXP est_complSEXP, SEXP ipw_complSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< double >::type est_compl(est_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_opt_s1_true(beta, t, data_compl, est_compl, ipw_compl));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_opt_s0_org
arma::colvec cpp_cox_opt_s0_org(double beta, arma::colvec t, arma::mat data_compl, arma::colvec ipw_compl);
RcppExport SEXP _twoStep2Phase_cpp_cox_opt_s0_org(SEXP betaSEXP, SEXP tSEXP, SEXP data_complSEXP, SEXP ipw_complSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_opt_s0_org(beta, t, data_compl, ipw_compl));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_opt_s1_org
arma::colvec cpp_cox_opt_s1_org(double beta, arma::colvec t, arma::mat data_compl, arma::colvec ipw_compl);
RcppExport SEXP _twoStep2Phase_cpp_cox_opt_s1_org(SEXP betaSEXP, SEXP tSEXP, SEXP data_complSEXP, SEXP ipw_complSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_opt_s1_org(beta, t, data_compl, ipw_compl));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_opt_s2_org
arma::colvec cpp_cox_opt_s2_org(double beta, arma::colvec t, arma::mat data_compl, arma::colvec ipw_compl);
RcppExport SEXP _twoStep2Phase_cpp_cox_opt_s2_org(SEXP betaSEXP, SEXP tSEXP, SEXP data_complSEXP, SEXP ipw_complSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_opt_s2_org(beta, t, data_compl, ipw_compl));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_opt_s0_work
arma::colvec cpp_cox_opt_s0_work(double beta, arma::colvec t, arma::mat data_all);
RcppExport SEXP _twoStep2Phase_cpp_cox_opt_s0_work(SEXP betaSEXP, SEXP tSEXP, SEXP data_allSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_opt_s0_work(beta, t, data_all));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_opt_s1_work
arma::colvec cpp_cox_opt_s1_work(double beta, arma::colvec t, arma::mat data_all);
RcppExport SEXP _twoStep2Phase_cpp_cox_opt_s1_work(SEXP betaSEXP, SEXP tSEXP, SEXP data_allSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_opt_s1_work(beta, t, data_all));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_opt_s2_work
arma::colvec cpp_cox_opt_s2_work(double beta, arma::colvec t, arma::mat data_all);
RcppExport SEXP _twoStep2Phase_cpp_cox_opt_s2_work(SEXP betaSEXP, SEXP tSEXP, SEXP data_allSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_opt_s2_work(beta, t, data_all));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_opt_score_work_kernel
double cpp_cox_opt_score_work_kernel(double beta, arma::mat data, arma::mat data_all, arma::mat data_compl, double h, double pi, double est_compl, arma::colvec ipw_compl, arma::colvec ipw);
RcppExport SEXP _twoStep2Phase_cpp_cox_opt_score_work_kernel(SEXP betaSEXP, SEXP dataSEXP, SEXP data_allSEXP, SEXP data_complSEXP, SEXP hSEXP, SEXP piSEXP, SEXP est_complSEXP, SEXP ipw_complSEXP, SEXP ipwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type est_compl(est_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw(ipwSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_opt_score_work_kernel(beta, data, data_all, data_compl, h, pi, est_compl, ipw_compl, ipw));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_opt_score_work_kernel_vec
arma::colvec cpp_cox_opt_score_work_kernel_vec(double beta, arma::mat data, arma::mat data_all, arma::mat data_compl, double h, double pi, double est_compl, arma::colvec ipw_compl, arma::colvec ipw);
RcppExport SEXP _twoStep2Phase_cpp_cox_opt_score_work_kernel_vec(SEXP betaSEXP, SEXP dataSEXP, SEXP data_allSEXP, SEXP data_complSEXP, SEXP hSEXP, SEXP piSEXP, SEXP est_complSEXP, SEXP ipw_complSEXP, SEXP ipwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type est_compl(est_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw(ipwSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_opt_score_work_kernel_vec(beta, data, data_all, data_compl, h, pi, est_compl, ipw_compl, ipw));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_opt_score_org
double cpp_cox_opt_score_org(double beta, arma::mat data, arma::mat data_all, arma::mat data_compl, arma::colvec ipw_compl, arma::colvec ipw);
RcppExport SEXP _twoStep2Phase_cpp_cox_opt_score_org(SEXP betaSEXP, SEXP dataSEXP, SEXP data_allSEXP, SEXP data_complSEXP, SEXP ipw_complSEXP, SEXP ipwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw(ipwSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_opt_score_org(beta, data, data_all, data_compl, ipw_compl, ipw));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_opt_score_org_vec
arma::colvec cpp_cox_opt_score_org_vec(double beta, arma::mat data, arma::mat data_all, arma::mat data_compl, arma::colvec ipw_compl, arma::colvec ipw);
RcppExport SEXP _twoStep2Phase_cpp_cox_opt_score_org_vec(SEXP betaSEXP, SEXP dataSEXP, SEXP data_allSEXP, SEXP data_complSEXP, SEXP ipw_complSEXP, SEXP ipwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw(ipwSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_opt_score_org_vec(beta, data, data_all, data_compl, ipw_compl, ipw));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_opt_info_org
double cpp_cox_opt_info_org(double beta, arma::mat data_all, arma::mat data_compl, arma::colvec ipw_compl);
RcppExport SEXP _twoStep2Phase_cpp_cox_opt_info_org(SEXP betaSEXP, SEXP data_allSEXP, SEXP data_complSEXP, SEXP ipw_complSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_compl(data_complSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw_compl(ipw_complSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_opt_info_org(beta, data_all, data_compl, ipw_compl));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_opt_score_work_coxph
double cpp_cox_opt_score_work_coxph(double beta, arma::mat data, arma::mat data_all, arma::colvec ipw);
RcppExport SEXP _twoStep2Phase_cpp_cox_opt_score_work_coxph(SEXP betaSEXP, SEXP dataSEXP, SEXP data_allSEXP, SEXP ipwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw(ipwSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_opt_score_work_coxph(beta, data, data_all, ipw));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_opt_score_work_coxph_vec
arma::colvec cpp_cox_opt_score_work_coxph_vec(double beta, arma::mat data, arma::mat data_all, arma::colvec ipw);
RcppExport SEXP _twoStep2Phase_cpp_cox_opt_score_work_coxph_vec(SEXP betaSEXP, SEXP dataSEXP, SEXP data_allSEXP, SEXP ipwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ipw(ipwSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_opt_score_work_coxph_vec(beta, data, data_all, ipw));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cox_opt_info_work_coxph
double cpp_cox_opt_info_work_coxph(double beta, arma::mat data_all);
RcppExport SEXP _twoStep2Phase_cpp_cox_opt_info_work_coxph(SEXP betaSEXP, SEXP data_allSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data_all(data_allSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cox_opt_info_work_coxph(beta, data_all));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_twoStep2Phase_cpp_cox_joint_lambda", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_lambda, 1},
    {"_twoStep2Phase_cpp_cox_joint_Lambda", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_Lambda, 1},
    {"_twoStep2Phase_cpp_cox_joint_log_normal_pdf", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_log_normal_pdf, 4},
    {"_twoStep2Phase_cpp_cox_joint_d_log_normal_pdf", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_d_log_normal_pdf, 3},
    {"_twoStep2Phase_cpp_cox_joint_dd_log_normal_pdf", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_dd_log_normal_pdf, 1},
    {"_twoStep2Phase_cpp_cox_joint_ddm_log_normal_pdf", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_ddm_log_normal_pdf, 1},
    {"_twoStep2Phase_cpp_cox_joint_est_Lambda", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_est_Lambda, 4},
    {"_twoStep2Phase_cpp_cox_joint_est_lambda", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_est_lambda, 3},
    {"_twoStep2Phase_cpp_cox_joint_s0_true", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_s0_true, 5},
    {"_twoStep2Phase_cpp_cox_joint_s1_true", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_s1_true, 5},
    {"_twoStep2Phase_cpp_cox_joint_s0_org", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_s0_org, 4},
    {"_twoStep2Phase_cpp_cox_joint_s1_org", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_s1_org, 4},
    {"_twoStep2Phase_cpp_cox_joint_s2_org", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_s2_org, 4},
    {"_twoStep2Phase_cpp_cox_joint_s0_work", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_s0_work, 3},
    {"_twoStep2Phase_cpp_cox_joint_s1_work", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_s1_work, 3},
    {"_twoStep2Phase_cpp_cox_joint_s2_work", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_s2_work, 3},
    {"_twoStep2Phase_cpp_cox_joint_score_work_modelX", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_score_work_modelX, 12},
    {"_twoStep2Phase_cpp_cox_joint_score_work_modelX_vec", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_score_work_modelX_vec, 12},
    {"_twoStep2Phase_cpp_cox_joint_score_work_trueX", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_score_work_trueX, 12},
    {"_twoStep2Phase_cpp_cox_joint_score_work_trueX_vec", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_score_work_trueX_vec, 12},
    {"_twoStep2Phase_cpp_cox_joint_score_org", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_score_org, 6},
    {"_twoStep2Phase_cpp_cox_joint_score_org_vec", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_score_org_vec, 6},
    {"_twoStep2Phase_cpp_cox_joint_info_org", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_info_org, 4},
    {"_twoStep2Phase_cpp_cox_joint_score_work_coxph", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_score_work_coxph, 4},
    {"_twoStep2Phase_cpp_cox_joint_score_work_coxph_vec", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_score_work_coxph_vec, 4},
    {"_twoStep2Phase_cpp_cox_joint_info_work_coxph", (DL_FUNC) &_twoStep2Phase_cpp_cox_joint_info_work_coxph, 2},
    {"_twoStep2Phase_cpp_cox_opt_lambda", (DL_FUNC) &_twoStep2Phase_cpp_cox_opt_lambda, 1},
    {"_twoStep2Phase_cpp_cox_opt_Lambda", (DL_FUNC) &_twoStep2Phase_cpp_cox_opt_Lambda, 1},
    {"_twoStep2Phase_cpp_cox_opt_log_kernel_fn", (DL_FUNC) &_twoStep2Phase_cpp_cox_opt_log_kernel_fn, 3},
    {"_twoStep2Phase_cpp_cox_opt_log_normal_pdf", (DL_FUNC) &_twoStep2Phase_cpp_cox_opt_log_normal_pdf, 4},
    {"_twoStep2Phase_cpp_cox_opt_est_Lambda", (DL_FUNC) &_twoStep2Phase_cpp_cox_opt_est_Lambda, 4},
    {"_twoStep2Phase_cpp_cox_opt_est_lambda", (DL_FUNC) &_twoStep2Phase_cpp_cox_opt_est_lambda, 3},
    {"_twoStep2Phase_cpp_cox_opt_s0_true", (DL_FUNC) &_twoStep2Phase_cpp_cox_opt_s0_true, 5},
    {"_twoStep2Phase_cpp_cox_opt_s1_true", (DL_FUNC) &_twoStep2Phase_cpp_cox_opt_s1_true, 5},
    {"_twoStep2Phase_cpp_cox_opt_s0_org", (DL_FUNC) &_twoStep2Phase_cpp_cox_opt_s0_org, 4},
    {"_twoStep2Phase_cpp_cox_opt_s1_org", (DL_FUNC) &_twoStep2Phase_cpp_cox_opt_s1_org, 4},
    {"_twoStep2Phase_cpp_cox_opt_s2_org", (DL_FUNC) &_twoStep2Phase_cpp_cox_opt_s2_org, 4},
    {"_twoStep2Phase_cpp_cox_opt_s0_work", (DL_FUNC) &_twoStep2Phase_cpp_cox_opt_s0_work, 3},
    {"_twoStep2Phase_cpp_cox_opt_s1_work", (DL_FUNC) &_twoStep2Phase_cpp_cox_opt_s1_work, 3},
    {"_twoStep2Phase_cpp_cox_opt_s2_work", (DL_FUNC) &_twoStep2Phase_cpp_cox_opt_s2_work, 3},
    {"_twoStep2Phase_cpp_cox_opt_score_work_kernel", (DL_FUNC) &_twoStep2Phase_cpp_cox_opt_score_work_kernel, 9},
    {"_twoStep2Phase_cpp_cox_opt_score_work_kernel_vec", (DL_FUNC) &_twoStep2Phase_cpp_cox_opt_score_work_kernel_vec, 9},
    {"_twoStep2Phase_cpp_cox_opt_score_org", (DL_FUNC) &_twoStep2Phase_cpp_cox_opt_score_org, 6},
    {"_twoStep2Phase_cpp_cox_opt_score_org_vec", (DL_FUNC) &_twoStep2Phase_cpp_cox_opt_score_org_vec, 6},
    {"_twoStep2Phase_cpp_cox_opt_info_org", (DL_FUNC) &_twoStep2Phase_cpp_cox_opt_info_org, 4},
    {"_twoStep2Phase_cpp_cox_opt_score_work_coxph", (DL_FUNC) &_twoStep2Phase_cpp_cox_opt_score_work_coxph, 4},
    {"_twoStep2Phase_cpp_cox_opt_score_work_coxph_vec", (DL_FUNC) &_twoStep2Phase_cpp_cox_opt_score_work_coxph_vec, 4},
    {"_twoStep2Phase_cpp_cox_opt_info_work_coxph", (DL_FUNC) &_twoStep2Phase_cpp_cox_opt_info_work_coxph, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_twoStep2Phase(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
