# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_cox_joint_lambda <- function(t) {
    .Call(`_twoStep2Phase_cpp_cox_joint_lambda`, t)
}

cpp_cox_joint_Lambda <- function(t) {
    .Call(`_twoStep2Phase_cpp_cox_joint_Lambda`, t)
}

cpp_cox_joint_log_normal_pdf <- function(t, m, s, pi) {
    .Call(`_twoStep2Phase_cpp_cox_joint_log_normal_pdf`, t, m, s, pi)
}

cpp_cox_joint_d_log_normal_pdf <- function(t, m, s) {
    .Call(`_twoStep2Phase_cpp_cox_joint_d_log_normal_pdf`, t, m, s)
}

cpp_cox_joint_dd_log_normal_pdf <- function(s) {
    .Call(`_twoStep2Phase_cpp_cox_joint_dd_log_normal_pdf`, s)
}

cpp_cox_joint_ddm_log_normal_pdf <- function(s) {
    .Call(`_twoStep2Phase_cpp_cox_joint_ddm_log_normal_pdf`, s)
}

cpp_cox_joint_est_Lambda <- function(t, data_compl, est_compl, ipw_compl) {
    .Call(`_twoStep2Phase_cpp_cox_joint_est_Lambda`, t, data_compl, est_compl, ipw_compl)
}

cpp_cox_joint_est_lambda <- function(data_compl, est_compl, ipw_compl) {
    .Call(`_twoStep2Phase_cpp_cox_joint_est_lambda`, data_compl, est_compl, ipw_compl)
}

cpp_cox_joint_s0_true <- function(beta, t, data_compl, est_compl, ipw_compl) {
    .Call(`_twoStep2Phase_cpp_cox_joint_s0_true`, beta, t, data_compl, est_compl, ipw_compl)
}

cpp_cox_joint_s1_true <- function(beta, t, data_compl, est_compl, ipw_compl) {
    .Call(`_twoStep2Phase_cpp_cox_joint_s1_true`, beta, t, data_compl, est_compl, ipw_compl)
}

cpp_cox_joint_s0_org <- function(beta, t, data_compl, ipw_compl) {
    .Call(`_twoStep2Phase_cpp_cox_joint_s0_org`, beta, t, data_compl, ipw_compl)
}

cpp_cox_joint_s1_org <- function(beta, t, data_compl, ipw_compl) {
    .Call(`_twoStep2Phase_cpp_cox_joint_s1_org`, beta, t, data_compl, ipw_compl)
}

cpp_cox_joint_s2_org <- function(beta, t, data_compl, ipw_compl) {
    .Call(`_twoStep2Phase_cpp_cox_joint_s2_org`, beta, t, data_compl, ipw_compl)
}

cpp_cox_joint_s0_work <- function(beta, t, data_all) {
    .Call(`_twoStep2Phase_cpp_cox_joint_s0_work`, beta, t, data_all)
}

cpp_cox_joint_s1_work <- function(beta, t, data_all) {
    .Call(`_twoStep2Phase_cpp_cox_joint_s1_work`, beta, t, data_all)
}

cpp_cox_joint_s2_work <- function(beta, t, data_all) {
    .Call(`_twoStep2Phase_cpp_cox_joint_s2_work`, beta, t, data_all)
}

cpp_cox_joint_score_work_modelX <- function(beta, data, data_all, data_compl, predX, seX, grid, weight, pi, est_compl, ipw_compl, ipw) {
    .Call(`_twoStep2Phase_cpp_cox_joint_score_work_modelX`, beta, data, data_all, data_compl, predX, seX, grid, weight, pi, est_compl, ipw_compl, ipw)
}

cpp_cox_joint_score_work_modelX_vec <- function(beta, data, data_all, data_compl, predX, seX, grid, weight, pi, est_compl, ipw_compl, ipw) {
    .Call(`_twoStep2Phase_cpp_cox_joint_score_work_modelX_vec`, beta, data, data_all, data_compl, predX, seX, grid, weight, pi, est_compl, ipw_compl, ipw)
}

cpp_cox_joint_score_work_trueX <- function(beta, data, data_all, data_compl, grid, weight, sde, theta, sdxz, pi, ipw_compl, ipw) {
    .Call(`_twoStep2Phase_cpp_cox_joint_score_work_trueX`, beta, data, data_all, data_compl, grid, weight, sde, theta, sdxz, pi, ipw_compl, ipw)
}

cpp_cox_joint_score_work_trueX_vec <- function(beta, data, data_all, data_compl, grid, weight, sde, theta, sdxz, pi, ipw_compl, ipw) {
    .Call(`_twoStep2Phase_cpp_cox_joint_score_work_trueX_vec`, beta, data, data_all, data_compl, grid, weight, sde, theta, sdxz, pi, ipw_compl, ipw)
}

cpp_cox_joint_score_org <- function(beta, data, data_all, data_compl, ipw_compl, ipw) {
    .Call(`_twoStep2Phase_cpp_cox_joint_score_org`, beta, data, data_all, data_compl, ipw_compl, ipw)
}

cpp_cox_joint_score_org_vec <- function(beta, data, data_all, data_compl, ipw_compl, ipw) {
    .Call(`_twoStep2Phase_cpp_cox_joint_score_org_vec`, beta, data, data_all, data_compl, ipw_compl, ipw)
}

cpp_cox_joint_info_org <- function(beta, data_all, data_compl, ipw_compl) {
    .Call(`_twoStep2Phase_cpp_cox_joint_info_org`, beta, data_all, data_compl, ipw_compl)
}

cpp_cox_joint_score_work_coxph <- function(beta, data, data_all, ipw) {
    .Call(`_twoStep2Phase_cpp_cox_joint_score_work_coxph`, beta, data, data_all, ipw)
}

cpp_cox_joint_score_work_coxph_vec <- function(beta, data, data_all, ipw) {
    .Call(`_twoStep2Phase_cpp_cox_joint_score_work_coxph_vec`, beta, data, data_all, ipw)
}

cpp_cox_joint_info_work_coxph <- function(beta, data_all) {
    .Call(`_twoStep2Phase_cpp_cox_joint_info_work_coxph`, beta, data_all)
}

cpp_cox_opt_lambda <- function(t) {
    .Call(`_twoStep2Phase_cpp_cox_opt_lambda`, t)
}

cpp_cox_opt_Lambda <- function(t) {
    .Call(`_twoStep2Phase_cpp_cox_opt_Lambda`, t)
}

cpp_cox_opt_log_kernel_fn <- function(t, h, pi) {
    .Call(`_twoStep2Phase_cpp_cox_opt_log_kernel_fn`, t, h, pi)
}

cpp_cox_opt_log_normal_pdf <- function(t, m, s, pi) {
    .Call(`_twoStep2Phase_cpp_cox_opt_log_normal_pdf`, t, m, s, pi)
}

cpp_cox_opt_est_Lambda <- function(t, data_compl, est_compl, ipw_compl) {
    .Call(`_twoStep2Phase_cpp_cox_opt_est_Lambda`, t, data_compl, est_compl, ipw_compl)
}

cpp_cox_opt_est_lambda <- function(data_compl, est_compl, ipw_compl) {
    .Call(`_twoStep2Phase_cpp_cox_opt_est_lambda`, data_compl, est_compl, ipw_compl)
}

cpp_cox_opt_s0_true <- function(beta, t, data_compl, est_compl, ipw_compl) {
    .Call(`_twoStep2Phase_cpp_cox_opt_s0_true`, beta, t, data_compl, est_compl, ipw_compl)
}

cpp_cox_opt_s1_true <- function(beta, t, data_compl, est_compl, ipw_compl) {
    .Call(`_twoStep2Phase_cpp_cox_opt_s1_true`, beta, t, data_compl, est_compl, ipw_compl)
}

cpp_cox_opt_s0_org <- function(beta, t, data_compl, ipw_compl) {
    .Call(`_twoStep2Phase_cpp_cox_opt_s0_org`, beta, t, data_compl, ipw_compl)
}

cpp_cox_opt_s1_org <- function(beta, t, data_compl, ipw_compl) {
    .Call(`_twoStep2Phase_cpp_cox_opt_s1_org`, beta, t, data_compl, ipw_compl)
}

cpp_cox_opt_s2_org <- function(beta, t, data_compl, ipw_compl) {
    .Call(`_twoStep2Phase_cpp_cox_opt_s2_org`, beta, t, data_compl, ipw_compl)
}

cpp_cox_opt_s0_work <- function(beta, t, data_all) {
    .Call(`_twoStep2Phase_cpp_cox_opt_s0_work`, beta, t, data_all)
}

cpp_cox_opt_s1_work <- function(beta, t, data_all) {
    .Call(`_twoStep2Phase_cpp_cox_opt_s1_work`, beta, t, data_all)
}

cpp_cox_opt_s2_work <- function(beta, t, data_all) {
    .Call(`_twoStep2Phase_cpp_cox_opt_s2_work`, beta, t, data_all)
}

cpp_cox_opt_score_work_kernel <- function(beta, data, data_all, data_compl, h, pi, est_compl, ipw_compl, ipw) {
    .Call(`_twoStep2Phase_cpp_cox_opt_score_work_kernel`, beta, data, data_all, data_compl, h, pi, est_compl, ipw_compl, ipw)
}

cpp_cox_opt_score_work_kernel_vec <- function(beta, data, data_all, data_compl, h, pi, est_compl, ipw_compl, ipw) {
    .Call(`_twoStep2Phase_cpp_cox_opt_score_work_kernel_vec`, beta, data, data_all, data_compl, h, pi, est_compl, ipw_compl, ipw)
}

cpp_cox_opt_score_org <- function(beta, data, data_all, data_compl, ipw_compl, ipw) {
    .Call(`_twoStep2Phase_cpp_cox_opt_score_org`, beta, data, data_all, data_compl, ipw_compl, ipw)
}

cpp_cox_opt_score_org_vec <- function(beta, data, data_all, data_compl, ipw_compl, ipw) {
    .Call(`_twoStep2Phase_cpp_cox_opt_score_org_vec`, beta, data, data_all, data_compl, ipw_compl, ipw)
}

cpp_cox_opt_info_org <- function(beta, data_all, data_compl, ipw_compl) {
    .Call(`_twoStep2Phase_cpp_cox_opt_info_org`, beta, data_all, data_compl, ipw_compl)
}

cpp_cox_opt_score_work_coxph <- function(beta, data, data_all, ipw) {
    .Call(`_twoStep2Phase_cpp_cox_opt_score_work_coxph`, beta, data, data_all, ipw)
}

cpp_cox_opt_score_work_coxph_vec <- function(beta, data, data_all, ipw) {
    .Call(`_twoStep2Phase_cpp_cox_opt_score_work_coxph_vec`, beta, data, data_all, ipw)
}

cpp_cox_opt_info_work_coxph <- function(beta, data_all) {
    .Call(`_twoStep2Phase_cpp_cox_opt_info_work_coxph`, beta, data_all)
}

